stages:
  - build
  - deploy
  - enable_merge

build_job:
  stage: build
  tags:
    - tomhp
  script:
    - ./scripts/buildPackage.sh
  artifacts:
    paths:
      - ./build_deb/
    expire_in: 4 week
  only:
    - master

deploy_job:
  stage: deploy
  tags:
    - tomhp
  script:
    - cd ./build_deb
    - cp * /media/volume1/ci_projects/snapshot/utilsCpp
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic utilscpp-dev
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic utilscpp-dbg
    - reprepro -b /media/volume1/reprepo/ -A source remove bionic utilscpp
    - reprepro --ignore=wrongdistribution --ignore=missingfield -b /media/volume1/reprepo/ -V include bionic utilscpp*_amd64.changes
    - cd .. 
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git remote set-url origin ssh://git@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - ./scripts/createTag.sh
  when: on_success
  only:
    - master

enable_merge:
  stage: enable_merge
  tags:
    - tomhp
  script:
    - ./scripts/buildPackage.sh
  artifacts:
    paths:
      - ./build_deb/
    expire_in: 1 days
  only:
    - merge_requests

